// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured. Run `flutterfire configure` to add web support.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions is not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv8gNOnyDGNjk02fjtw4eWkLpX2oHMFQ',
    appId: '1:515666520248:android:14c5e830125995470f2c4d',
    messagingSenderId: '515666520248',
    projectId: 'tarana-app-587f9',
    storageBucket: 'tarana-app-587f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWwUGH4boX0Wo6wLStO0-dAMOfsZqzdU',
    appId: '1:515666520248:ios:0e35912e54a950f90f2c4d',
    messagingSenderId: '515666520248',
    projectId: 'tarana-app-587f9',
    storageBucket: 'tarana-app-587f9.firebasestorage.app',
    iosBundleId: 'com.example.tarana',
  );
}
