import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:provider/provider.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../shared/enums/booking_status.dart';
import '../../../shared/enums/payment_method.dart';
import '../../providers/auth_provider.dart';
import '../../providers/booking_provider.dart';
import '../../providers/map_provider.dart';
import '../../../data/models/booking_model.dart';
import '../../widgets/common/gradient_button.dart';
import '../../widgets/map/map_view.dart';

class BookingConfirmationScreen extends StatefulWidget {
  final String pickupAddress;
  final String dropoffAddress;

  const BookingConfirmationScreen({
    super.key,
    required this.pickupAddress,
    required this.dropoffAddress,
  });

  @override
  State<BookingConfirmationScreen> createState() =>
      _BookingConfirmationScreenState();
}

class _BookingConfirmationScreenState extends State<BookingConfirmationScreen> {
  final LatLng _mockPickup = const LatLng(14.5995, 120.9842); // Manila
  final LatLng _mockDropoff = const LatLng(14.5547, 121.0244); // Makati

  bool _isScheduled = false;
  DateTime? _scheduledAt;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _loadRoute();
    });
  }

  Future<void> _loadRoute() async {
    final mapProvider = context.read<MapProvider>();
    await mapProvider.drawRoute(_mockPickup, _mockDropoff);
  }

  void _confirmBooking() async {
    final authProvider = context.read<AuthProvider>();
    final bookingProvider = context.read<BookingProvider>();
    final mapProvider = context.read<MapProvider>();

    if (authProvider.user == null) return;

    final distanceKm = mapProvider.currentRoute?.distanceValue != null
        ? mapProvider.currentRoute!.distanceValue / 1000.0
        : 5.0; // Fallback to 5km

    final durationMins = mapProvider.currentRoute?.durationValue != null
        ? mapProvider.currentRoute!.durationValue / 60.0
        : 15.0; // Fallback to 15 mins

    // Simple fare calculation: Base 50 + 15/km + 2/min
    final baseFare = 50.0;
    final distFare = distanceKm * 15.0;
    final timeFare = durationMins * 2.0;
    final totalFare = baseFare + distFare + timeFare;

    final booking = BookingModel(
      id: '', // Will be generated by Firestore
      riderId: authProvider.user!.uid,
      status: BookingStatus.searching,
      pickup: BookingLocation(
        lat: _mockPickup.latitude,
        lng: _mockPickup.longitude,
        address: widget.pickupAddress,
      ),
      dropoff: BookingLocation(
        lat: _mockDropoff.latitude,
        lng: _mockDropoff.longitude,
        address: widget.dropoffAddress,
      ),
      fare: BookingFare(
        baseFare: baseFare,
        distanceFare: distFare,
        timeFare: timeFare,
        surgeMultiplier: 1.0,
        discount: 0.0,
        total: totalFare,
        currency: 'PHP',
      ),
      isScheduled: _isScheduled,
      scheduledAt: _isScheduled ? _scheduledAt : null,
      paymentMethod: PaymentMethod.cash,
      paymentStatus: 'pending',
      distanceKm: distanceKm,
      durationMinutes: durationMins,
      routePolyline:
          mapProvider.currentRoute?.polylinePoints
              .map((p) => '${p.latitude},${p.longitude}')
              .join('|') ??
          '',
      requestedAt: DateTime.now(),
    );

    await bookingProvider.requestRide(booking);

    if (mounted) {
      if (bookingProvider.error != null) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(bookingProvider.error!)));
      } else {
        context.pushReplacement(
          '/booking/trip',
        ); // Proceed to trip finding screen
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final mapProvider = context.watch<MapProvider>();

    // Simple fare estimation for display
    final distanceKm = mapProvider.currentRoute?.distanceValue != null
        ? mapProvider.currentRoute!.distanceValue / 1000.0
        : 5.0;
    final durationMins = mapProvider.currentRoute?.durationValue != null
        ? mapProvider.currentRoute!.durationValue / 60.0
        : 15.0;
    final totalFare = 50.0 + (distanceKm * 15.0) + (durationMins * 2.0);

    return Scaffold(
      backgroundColor: AppColors.background,
      body: Stack(
        children: [
          // Background Map Layer
          const MapView(),

          // Back Button top left
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: CircleAvatar(
                backgroundColor: AppColors.surface,
                child: IconButton(
                  icon: const Icon(
                    Icons.arrow_back_ios_rounded,
                    color: AppColors.textPrimary,
                  ),
                  onPressed: () {
                    context.read<MapProvider>().clearRoute();
                    context.pop();
                  },
                ),
              ),
            ),
          ),

          // Bottom Confirmation Sheet
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: Container(
              decoration: const BoxDecoration(
                color: AppColors.surface,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(24),
                  topRight: Radius.circular(24),
                ),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black12,
                    blurRadius: 20,
                    offset: Offset(0, -5),
                  ),
                ],
              ),
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text('Ride Details', style: AppTextStyles.h4),
                      if (mapProvider.currentRoute != null)
                        Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 12,
                            vertical: 6,
                          ),
                          decoration: BoxDecoration(
                            color: AppColors.primaryLight.withAlpha(
                              (0.2 * 255).round(),
                            ),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Text(
                            mapProvider.currentRoute!.durationText,
                            style: AppTextStyles.bodyMedium.copyWith(
                              color: AppColors.primary,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Locations
                  Row(
                    children: [
                      Column(
                        children: [
                          const Icon(
                            Icons.my_location_rounded,
                            color: AppColors.success,
                            size: 16,
                          ),
                          Container(
                            width: 2,
                            height: 24,
                            color: AppColors.border,
                          ),
                          const Icon(
                            Icons.location_on_rounded,
                            color: AppColors.error,
                            size: 16,
                          ),
                        ],
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              widget.pickupAddress,
                              style: AppTextStyles.bodyMedium,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                            const SizedBox(height: 16),
                            Text(
                              widget.dropoffAddress,
                              style: AppTextStyles.bodyMedium,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),

                  const Padding(
                    padding: EdgeInsets.symmetric(vertical: 16),
                    child: Divider(),
                  ),

                  // Car Type Selection
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      border: Border.all(color: AppColors.primary, width: 2),
                      borderRadius: BorderRadius.circular(16),
                      color: AppColors.primaryLight.withAlpha(
                        (0.1 * 255).round(),
                      ),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Row(
                          children: [
                            const Icon(
                              Icons.directions_car_rounded,
                              size: 36,
                              color: AppColors.primary,
                            ),
                            const SizedBox(width: 12),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'TaranaX',
                                  style: AppTextStyles.bodyLarge.copyWith(
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                Text(
                                  '4 seats • Affordable',
                                  style: AppTextStyles.caption,
                                ),
                              ],
                            ),
                          ],
                        ),
                        Text(
                          '₱${totalFare.toStringAsFixed(2)}',
                          style: AppTextStyles.h4.copyWith(
                            color: AppColors.primary,
                          ),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 24),

                  // Schedule ride
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      border: Border.all(color: AppColors.border),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Column(
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Row(
                              children: [
                                const Icon(
                                  Icons.schedule_rounded,
                                  color: AppColors.primary,
                                ),
                                const SizedBox(width: 12),
                                Text(
                                  'Schedule for later',
                                  style: AppTextStyles.bodyMedium,
                                ),
                              ],
                            ),
                            Switch.adaptive(
                              value: _isScheduled,
                              activeColor: AppColors.primary,
                              onChanged: (value) {
                                setState(() {
                                  _isScheduled = value;
                                  if (value && _scheduledAt == null) {
                                    _scheduledAt = DateTime.now().add(
                                      const Duration(hours: 1),
                                    );
                                  }
                                });
                              },
                            ),
                          ],
                        ),
                        if (_isScheduled && _scheduledAt != null) ...[
                          const SizedBox(height: 8),
                          GestureDetector(
                            onTap: () async {
                              final date = await showDatePicker(
                                context: context,
                                initialDate: _scheduledAt!,
                                firstDate: DateTime.now(),
                                lastDate: DateTime.now().add(
                                  const Duration(days: 7),
                                ),
                              );
                              if (date != null && mounted) {
                                final time = await showTimePicker(
                                  context: context,
                                  initialTime: TimeOfDay.fromDateTime(
                                    _scheduledAt!,
                                  ),
                                );
                                if (time != null) {
                                  setState(() {
                                    _scheduledAt = DateTime(
                                      date.year,
                                      date.month,
                                      date.day,
                                      time.hour,
                                      time.minute,
                                    );
                                  });
                                }
                              }
                            },
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 16,
                                vertical: 12,
                              ),
                              decoration: BoxDecoration(
                                color: AppColors.primaryLight.withAlpha(
                                  (0.1 * 255).round(),
                                ),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Row(
                                children: [
                                  const Icon(
                                    Icons.calendar_today_rounded,
                                    size: 18,
                                    color: AppColors.primary,
                                  ),
                                  const SizedBox(width: 8),
                                  Text(
                                    '${_scheduledAt!.day}/${_scheduledAt!.month}/${_scheduledAt!.year} at ${_scheduledAt!.hour.toString().padLeft(2, '0')}:${_scheduledAt!.minute.toString().padLeft(2, '0')}',
                                    style: AppTextStyles.bodyMedium.copyWith(
                                      color: AppColors.primary,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                  const Spacer(),
                                  const Icon(
                                    Icons.edit_rounded,
                                    size: 16,
                                    color: AppColors.primary,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),

                  // Payment method
                  const SizedBox(height: 12),
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      border: Border.all(color: AppColors.border),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Row(
                      children: [
                        const Icon(
                          Icons.payments_rounded,
                          color: AppColors.success,
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Cash',
                                style: AppTextStyles.bodyMedium.copyWith(
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              Text(
                                'Pay driver in cash',
                                style: AppTextStyles.caption,
                              ),
                            ],
                          ),
                        ),
                        const Icon(
                          Icons.check_circle_rounded,
                          color: AppColors.success,
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 24),

                  Consumer<BookingProvider>(
                    builder: (context, bookingProvider, child) {
                      return GradientButton(
                        text: 'Confirm Booking',
                        isLoading:
                            bookingProvider.isLoading ||
                            mapProvider.isLoadingRoute,
                        onPressed: _confirmBooking,
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
